### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)  CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by HanGuo97** [nocaps-org/image-feature-extractors#1]
Hi KD,

Thanks again for providing the code!

I have been trying to run the feature extraction according to the README, with no changes to the code apart from changing some paths. The first step worked just fine. While I was running the second stage (extracting VG features using OI boxes), the script crashed and showed a CUDNN error. I have attached the errors below.

Thanks,
Han

![Screen Shot 2019-08-14 at 3 18 35 PM](https://user-images.githubusercontent.com/18187806/63060336-caeeb180-bea6-11e9-983a-10b5c3b08b59.png)

GPU: `V100`
Driver Version: `418.67`

Command I used:
```shell
python scripts/extract_features_vg.py \
    --prototxt models/vg_faster_rcnn_end2end/test_force_boxes.prototxt \
    --force-boxes /nlp/DATA/CaptionsData/COCO/val2017/detections.json \
    --caffemodel models/vg_faster_rcnn_end2end/resnet101_faster_rcnn_final.caffemodel \
    --images /nlp/DATA/CaptionsData/COCO/val2017/ \
    --annotations /nlp/han/DLResearch/DATA/CaptionsData/COCO/annotations/captions_val2017.json \
    --output /nlp/DATA/CaptionsData/COCO/val2017/features.h5
```

**Comment by kdexd** [comment]
Hi Han,

I am unable to reproduce this issue so far, I'll keep you posted on ho this goes.

**Comment by HanGuo97** [comment]
Hi KD,

Do you mind specifying the GPU(s) and Driver Version used in your machine setup?

**Comment by kdexd** [comment]
We used `TitanX` with driver version `418.67`.

**Comment by aleSuglia** [comment]
Got the same error specified here. @HanGuo97 did you find a  solution?

**Comment by HanGuo97** [comment]
The issue turned out to be related to CUDA versions. I raised the CUDA and NCCL version and things worked well for me.
